"useclient";
import{useState}from"react";
importLinkfrom"next/link";
import{format}from"date-fns";
import{vi}from"date-fns/locale";
import{Button}from"@/components/ui/button";
import{
Card,
CardContent,
CardDescription,
CardHeader,
CardTitle,
}from"@/components/ui/card";
import{
Table,
TableBody,
TableCell,
TableHead,
TableHeader,
TableRow,
}from"@/components/ui/table";
import{Badge}from"@/components/ui/badge";
import{PaymentStatusBadge}from"@/components/PaymentStatusBadge";
//Mockdata-replacewithAPIcall
constmockPayments=[
{
id:"PAY-001",
amount:5000000,
currency:"VND",
status:"completed"asconst,
method:"CreditCard",
description:"GóiBrandOwner-Tháng11/2025",
date:newDate("2025-05-01T10:30:00"),
invoiceId:"inv_001",
},
{
id:"PAY-002",
amount:5000000,
currency:"VND",
status:"pending"asconst,
method:"BankTransfer",
description:"GóiBrandOwner-Tháng10/2025",
date:newDate("2025-05-03T14:15:00"),
invoiceId:"inv_002",
},
{
id:"PAY-003",
amount:5000000,
currency:"VND",
status:"failed"asconst,
method:"Momo",
description:"GóiBrandOwner-Tháng11/2025",
date:newDate("2025-05-05T09:45:00"),
invoiceId:"inv_003",
},
{
id:"PAY-004",
amount:5000000,
currency:"VND",
status:"refunded"asconst,
method:"CreditCard",
description:"GóiBrandOwner-Tháng12/2025(giảm20%)",
date:newDate("2025-06-01T11:00:00"),
invoiceId:"inv_004",
},
{
id:"PAY-005",
amount:5000000,
currency:"VND",
status:"failed"asconst,
method:"CreditCard",
description:"GóiBrandOwner-Tháng01/2025",
date:newDate("2025-06-10T16:20:00"),
invoiceId:"INV-005",
},
];
exportdefaultfunctionPaymentsPage(){
const[filter,setFilter]=useState<"all"|"completed"|"pending"|"failed">("all");
constfilteredPayments=mockPayments.filter((payment)=>{
if(filter==="all")returntrue;
returnpayment.status===filter;
});
consttotalPaid=mockPayments
.filter((p)=>p.status==="completed")
.reduce((sum,p)=>sum+p.amount,0);
return(
<divclassName="min-h-screenbg-gradient-to-brfrom-slate-50via-whiteto-blue-50">
{/*Header*/}
<headerclassName="border-bbg-white/80backdrop-blur">
<divclassName="containermx-autoflexitems-centerjustify-betweenpx-6py-4">
<Linkhref="/"className="flexitems-centerspace-x-3">
<divclassName="flexitems-centerspace-x-2">
<imgsrc="/logo.svg"alt="FragoLogo"className="h-16w-auto"/>
</div>
</Link>
<divclassName="flexitems-centergap-3">
<Linkhref="/dashboard">
<Buttonvariant="ghost"className="text-slate-700">
Dashboard
</Button>
</Link>
<Linkhref="/profile">
<Buttonvariant="outline"className="border-slate-200">
Hồsơ
</Button>
</Link>
</div>
</div>
</header>
<mainclassName="containermx-autopx-6py-8">

{/*PageHeader*/}
<divclassName="mb-8">
<h1className="text-3xlfont-boldtext-slate-900">Lịchsửthanhtoán</h1>
<pclassName="mt-2text-slate-600">
Quảnlývàtheodõitấtcảcácgiaodịchthanhtoáncủabạn
</p>
</div>
{/*StatsCards*/}
<divclassName="gridgrid-cols-1sm:grid-cols-3gap-4mb-8">
<Card>
<CardHeader>
<CardTitle>Tổngthanhtoán</CardTitle>
<CardDescription>Tổngtiềnđãthanhtoán</CardDescription>
</CardHeader>
<CardContent>
<divclassName="text-2xlfont-semibold">{totalPaid.toLocaleString()}VND</div>
</CardContent>
</Card>
<Card>
<CardHeader>
<CardTitle>Tổnggiaodịch</CardTitle>
<CardDescription>Tổngsốgiaodịch</CardDescription>
</CardHeader>
<CardContent>
<divclassName="text-2xlfont-semibold">{mockPayments.length}</div>
</CardContent>
</Card>
<Card>
<CardHeader>
<CardTitle>Trạngthái</CardTitle>
<CardDescription>Lọctheotrạngthái</CardDescription>
</CardHeader>
<CardContent>
<divclassName="flexgap-2">
<Buttonvariant={filter==="all"?"default":"ghost"}onClick={()=>setFilter("all")}>Tấtcả</Button>
<Buttonvariant={filter==="completed"?"default":"ghost"}onClick={()=>setFilter("completed")}>Hoànthành</Button>
<Buttonvariant={filter==="pending"?"default":"ghost"}onClick={()=>setFilter("pending")}>Đangxửlý</Button>
<Buttonvariant={filter==="failed"?"default":"ghost"}onClick={()=>setFilter("failed")}>Thấtbại</Button>
</div>
</CardContent>
</Card>
</div>
{/*PaymentsTable*/}
<Card>
<CardHeader>
<CardTitle>Danhsáchgiaodịch</CardTitle>
<CardDescription>Hiểnthịcácgiaodịchgầnđây</CardDescription>
</CardHeader>
<CardContent>
<Table>
<TableHeader>
<TableRow>
<TableHead>Id</TableHead>
<TableHead>Môtả</TableHead>
<TableHead>Ngày</TableHead>
<TableHead>Phươngthức</TableHead>
<TableHead>Sốtiền</TableHead>
<TableHeadclassName="text-center">Trạngthái</TableHead>
<TableHeadclassName="text-right">Hànhđộng</TableHead>
</TableRow>
</TableHeader>
<TableBody>
{filteredPayments.length===0?(
<TableRow>
<TableCellcolSpan={7}className="text-centertext-slate-500">
Khôngcógiaodịchnào</TableCell>
</TableRow>
):(filteredPayments.map((payment)=>(
<TableRowkey={payment.id}>
<TableCellclassName="font-monotext-sm">{payment.id}</TableCell>
<TableCell>
<div>
<pclassName="font-mediumtext-slate-900">
{payment.description}
</p>
<pclassName="text-xstext-slate-500">
{payment.invoiceId}
</p>
</div>
</TableCell>
<TableCellclassName="text-smtext-slate-600">
{format(payment.date,"dd/MM/yyyy",{locale:vi})}
</TableCell>
<TableCell>
<Badgevariant="outline"className="text-xs">
{payment.method}
</Badge>
</TableCell>
<TableCellclassName="font-semiboldtext-slate-900">
{payment.amount.toLocaleString("vi-VN")}đ
</TableCell>
<TableCell>
<PaymentStatusBadgestatus={payment.status}/>
</TableCell>
<TableCellclassName="text-right">
<Linkhref={`/payments/${payment.id}`}>
<Buttonvariant="ghost"size="sm">
Chitiết
</Button>
</Link>
</TableCell>
</TableRow>
))
)}
</TableBody>
</Table>
</CardContent>
</Card>
</main>
</div>
);
}