"useclient";
import{use,useState}from"react";
importLinkfrom"next/link";
import{useRouter}from"next/navigation";
import{format}from"date-fns";
import{vi}from"date-fns/locale";
import{Button}from"@/components/ui/button";
import{
Card,
CardContent,
CardDescription,
CardHeader,
CardTitle,
}from"@/components/ui/card";
import{Separator}from"@/components/ui/separator";
import{Badge}from"@/components/ui/badge";
import{PaymentStatusBadge}from"@/components/PaymentStatusBadge";
//InlinefallbackPaymentTimelinetoavoidmissingmoduleerror(replacewithrealcomponentlater)
constPaymentTimeline=({events=[]}:any)=>{
return(
<divclassName="space-y-4">
{events.map((ev:any,idx:number)=>(
<divkey={ev.id||idx}className="relativeflexgap-3pb-4last:pb-0">
{/*Timelinedot*/}
<divclassName="flexflex-colitems-center">
<divclassName={`h-3w-3rounded-full${
ev.type==='success'?'bg-green-500':
ev.type==='error'?'bg-red-500':
ev.type==='warning'?'bg-yellow-500':
'bg-blue-500'
}`}/>
{idx<events.length-1&&(
<divclassName="w-pxflex-1bg-slate-200mt-1"style={{minHeight:'20px'}}/>
)}
</div>
{/*Content*/}
<divclassName="flex-1pt-0">
<pclassName="text-smfont-mediumtext-slate-900">{ev.title}</p>
<pclassName="text-xstext-slate-500mt-0.5">{ev.description}</p>
<pclassName="text-xstext-slate-400mt-1">
{format(newDate(ev.timestamp),"dd/MM/yyyyHH:mm:ss",{locale:vi})}
</p>
</div>
</div>
))}
</div>
);
};
//Mockdata-replacewithAPIcall
constmockPaymentsData:Record<string,any>={
"PAY-001":{
id:"PAY-001",
amount:1500000,
currency:"VND",
status:"completed"asconst,
method:"Thẻtíndụng",
cardLast4:"4242",
description:"GóiBrandOwner-Tháng11/2025",
date:newDate("2025-11-01T10:30:00"),
invoiceNumber:"INV-2025-001",
billingEmail:"user@example.com",
billingName:"NguyễnVănA",
billingAddress:"123ĐườngABC,Quận1,TP.HCM",
taxId:"0123456789",
subtotal:1500000,
tax:0,
total:1500000,
timeline:[
{id:"1",
title:"Thanhtoánthànhcông",
description:"Giaodịchđãđượcxửlýthànhcông",
timestamp:newDate("2025-11-01T10:30:15"),
type:"success"asconst,
},
{id:"2",
title:"Đangxửlýthanhtoán",
description:"Hệthốngđangxácthựcthôngtinthanhtoán",
timestamp:newDate("2025-11-01T10:30:05"),
type:"success"asconst,
},
{id:"2",
title:"Đangxửlýthanhtoán",
description:"Hệthốngđangxácthựcthôngtinthanhtoán",
timestamp:newDate("2025-11-01T10:30:05"),
type:"info"asconst,
},
{id:"3",
title:"Khởitạogiaodịch",
description:"Yêucầuthanhtoánđãđượctạo",
timestamp:newDate("2025-11-01T10:30:00"),
type:"info"asconst,
},
],
},
"PAY-002":{
id:"PAY-002",
amount:1500000,
currency:"VND",
status:"completed"asconst,
method:"Chuyểnkhoản",
bankName:"Vietcombank",
accountNumber:"1234567890",
description:"GóiBrandOwner-Tháng10/2025",
date:newDate("2025-10-01T14:20:00"),
invoiceNumber:"INV-2025-002",
billingEmail:"user@example.com",
billingName:"NguyễnVănA",
billingAddress:"123ĐườngABC,Quận1,TP.HCM",
taxId:"0123456789",
subtotal:1500000,
tax:0,
total:1500000,
timeline:[
{
id:"1",
title:"Thanhtoánthànhcông",
description:"Giaodịchđãđượcxửlýthànhcông",
timestamp:newDate("2025-10-01T14:20:30"),
type:"success"asconst,
},
{
id:"2",
title:"Đangxửlýthanhtoán",
description:"Hệthốngđangxácthựcthôngtinthanhtoán",
timestamp:newDate("2025-10-01T14:20:15"),
type:"success"asconst,
},
{
id:"3",
title:"Khởitạogiaodịch",
description:"Yêucầuthanhtoánđãđượctạo",
timestamp:newDate("2025-10-01T14:20:00"),
type:"info"asconst,
},
],
},
"PAY-003":{
id:"PAY-003",
amount:1500000,
currency:"VND",
status:"pending"asconst,
method:"Thẻtíndụng",
cardLast4:"1234",
description:"GóiBrandOwner-Tháng12/2025",
date:newDate("2025-12-01T09:15:00"),
invoiceNumber:"INV-2024-003",
billingEmail:"user@example.com",
billingName:"NguyễnVănA",
billingAddress:"123ĐườngABC,Quận1,TP.HCM",
taxId:"0123456789",
subtotal:1500000,
tax:0,
total:1500000,
timeline:[
{id:"1",
title:"Đangxửlýthanhtoán",
description:"Hệthốngđangxácthựcthôngtinthanhtoán",
timestamp:newDate("2025-12-01T09:15:20"),
type:"warning"asconst,
},
{id:"2",
title:"Khởitạogiaodịch",
description:"Yêucầuthanhtoánđãđượctạo",
timestamp:newDate("2025-12-01T09:15:00"),
type:"info"asconst,
},
],
},
"PAY-004":{
id:"PAY-004",
amount:14400000,
currency:"VND",
status:"completed"asconst,
method:"Chuyểnkhoản",
bankName:"Techcombank",
accountNumber:"0987654321",
description:"GóiBrandOwner-Năm2025",
date:newDate("2024-01-01T11:00:00"),
invoiceNumber:"INV-2024-004",
billingEmail:"user@example.com",
billingName:"NguyễnVănA",
billingAddress:"123ĐườngABC,Quận1,TP.HCM",
taxId:"0123456789",
subtotal:18000000,
discount:3600000,
tax:0,
total:14400000,
timeline:[
{
id:"1",
title:"Thanhtoánthànhcông",
description:"Giaodịchđãđượcxửlýthànhcông",
timestamp:newDate("2025-01-01T11:00:30"),
type:"success"asconst,
},
{
id:"2",
title:"Đangxửlýthanhtoán",
description:"Hệthốngđangxácthựcthôngtinthanhtoán",
timestamp:newDate("2025-01-01T11:00:15"),
type:"success"asconst,
},
{
id:"3",
title:"Khởitạogiaodịch",
description:"Yêucầuthanhtoánđãđượctạo",
timestamp:newDate("2024-01-01T11:00:00"),
type:"info"asconst,
},
],
},
"PAY-005":{
id:"PAY-005",
amount:1500000,
currency:"VND",
status:"failed"asconst,
method:"Thẻtíndụng",
cardLast4:"5678",
description:"GóiBrandOwner-Tháng09/2024",
date:newDate("2024-09-01T13:45:00"),
invoiceNumber:"INV-2024-005",
billingEmail:"user@example.com",
billingName:"NguyễnVănA",
billingAddress:"123ĐườngABC,Quận1,TP.HCM",
taxId:"0123456789",
subtotal:1500000,
tax:0,
total:1500000,
failureReason:"Sốdưkhôngđủ",
timeline:[
{
id:"1",
title:"Thanhtoánthấtbại",
description:"Giaodịchkhôngthànhcôngdolỗixácthực",
timestamp:newDate("2024-09-01T13:45:20"),
type:"error"asconst,
},
{
id:"2",
title:"Đangxửlýthanhtoán",
description:"Hệthốngđangxácthựcthôngtinthanhtoán",
timestamp:newDate("2024-09-01T13:45:10"),
type:"info"asconst,
},
{
id:"3",
title:"Khởitạogiaodịch",
description:"Yêucầuthanhtoánđãđượctạo",
timestamp:newDate("2024-09-01T13:45:00"),
type:"info"asconst,
},
],
},
};
exportdefaultfunctionPaymentDetailPage({
params,
}:{
params:Promise<{id:string}>;
}){
constrouter=useRouter();
const{id}=use(params);
constpayment=mockPaymentsData[id];
if(!payment){
return(
<divclassName="flexmin-h-screenitems-centerjustify-centerbg-gradient-to-brfrom-slate-50via-whiteto-blue-50">
<CardclassName="w-fullmax-w-md">
<CardHeader>
<CardTitle>Khôngtìmthấygiaodịch</CardTitle>
<CardDescription>
GiaodịchvớiID<strong>{id}</strong>khôngtồntại.
</CardDescription>
</CardHeader>
<CardContent>
<Linkhref="/payments">
<ButtonclassName="w-full">Quaylạidanhsách</Button>
</Link>
</CardContent>
</Card>
</div>
);
}
consthandleDownloadInvoice=()=>{
//Implementinvoicedownloadlogic
alert("Tínhnăngtảihóađơnsẽđượctriểnkhai");
};
return(
<divclassName="min-h-screenbg-gradient-to-brfrom-slate-50via-whiteto-blue-50">
{/*Header*/}
<headerclassName="border-bbg-white/80backdrop-blur">
<divclassName="containermx-autoflexitems-centerjustify-betweenpx-6py-4">
<Linkhref="/"className="flexitems-centerspace-x-3">
<divclassName="flexitems-centerspace-x-2">
<img
src="/logo.svg"
alt="FragoLogo"
className="h-16w-auto"
/>
</div>
<div>
<pclassName="text-basefont-boldtext-slate-900">Chitiếtthanhtoán</p>
</div>
</Link>
<divclassName="flexitems-centergap-3"></div>
<divclassName="flexitems-centergap-2">
<Linkhref="/payments">
<Buttonvariant="ghost"className="text-slate-700">quaylại</Button>
</Link>
<Buttonvariant="outline"className="border-slate-200"onClick={handleDownloadInvoice}>Tảihóađơn</Button>
</div>
</div>
</header>

<mainclassName="containermx-autop-6">
<divclassName="gridgrid-cols-1lg:grid-cols-3gap-6">
<CardclassName="lg:col-span-2">
<CardHeader>
<CardTitle>Thôngtingiaodịch</CardTitle>
<CardDescription>Giaodịch{payment.id}—{format(payment.date,"PPpp",{locale:vi})}</CardDescription>
</CardHeader>
<CardContent>
<divclassName="space-y-2">
<divclassName="flexitems-centerjustify-between">
<divclassName="text-smtext-slate-600">Sốtiền</div>
<divclassName="font-medium">{payment.amount.toLocaleString("vi-VN")}{payment.currency}</div>
</div>
<divclassName="flexitems-centerjustify-between">
<divclassName="text-smtext-slate-600">Phươngthức</div>
<divclassName="font-medium">{payment.method}</div>
</div>
<divclassName="flexitems-centerjustify-between">
<divclassName="text-smtext-slate-600">Trạngthái</div>
<PaymentStatusBadgestatus={payment.status}/>
</div>
</div>
<SeparatorclassName="my-4"/>
<div>
<h4className="text-smfont-semiboldmb-2">Timeline</h4>
<PaymentTimelineevents={payment.timeline}/>
</div>
</CardContent>
</Card>

<Card>
<CardHeader>
<CardTitle>Hóađơn</CardTitle>
<CardDescription>Chitiếtvềgiaodịchnày</CardDescription>
</CardHeader>
<CardContent>
<divclassName="space-y-2text-sm">
<pclassName="text-smfont-mediumtext-slate-500">Mãgiaodịch</p>
<pclassName="mt-1font-monotext-smfont-semiboldtext-slate-900">{payment.id}</p>
</div><div>
<pclassName="text-smfont-mediumtext-slate-500">Sốhóađơn</p>
<pclassName="mt-1font-monotext-smfont-semiboldtext-slate-900">
{payment.invoiceNumber}
</p>
</div>
<div>
<pclassName="text-smfont-mediumtext-slate-500">Phươngthức</p>
<pclassName="mt-1text-smfont-semiboldtext-slate-900"></p>
{payment.method}
</div>
<div><pclassName="text-smfont-mediumtext-slate-500">Ngàygiaodịch</p>
<pclassName="mt-1text-smfont-semiboldtext-slate-900">
{format(payment.date,"dd/MM/yyyyHH:mm",{locale:vi})}
</p>
</div>
<div>
</div><Separator/>
{/*PaymentMethodDetails*/}
{payment.cardLast4&&(
<divclassName="rounded-lgbg-slate-50p-4">
<pclassName="text-smfont-mediumtext-slate-700">Phươngthứcthanhtoán</p>
<divclassName="mt-2flexitems-centergap-2">
<Badgevariant="outline">{payment.cardBrand}</Badge>
<spanclassName="font-monotext-sm">************{payment.cardLast4}</span>
</div>
</div>
)}
{payment.bankName&&(
<divclassName="rounded-lgbg-slate-50p-4">
<pclassName="text-smfont-mediumtext-slate-700">Thôngtinchuyểnkhoản</p>
<divclassName="mt-2space-y-1">
<pclassName="text-smtext-slate-900">
<spanclassName="font-medium">Ngânhàng:</span>{""}{payment.bankName}
</p>
<pclassName="font-monotext-smtext-slate-900">
<spanclassName="font-medium">STK:</span>{""}{payment.accountNumber}
</p>
</div>
</div>
)}
{payment.failureReason&&(
<divclassName="rounded-lgbg-red-50p-4">
<pclassName="text-smfont-mediumtext-red-700">
Lýdothấtbại
</p>
<pclassName="mt-1text-smtext-red-600">{payment.failureReason}</p>
</div>
)}
<Separator/>
<div>
<pclassName="text-smfont-mediumtext-slate-500">Môtả</p>
<pclassName="mt-1text-smtext-slate-900">{payment.description}</p>
</div>
</CardContent>
</Card>
{/*InvoiceDetails*/}
<Card><CardHeader>
<CardTitle>Chitiếthóađơn</CardTitle>
<CardDescription>Thôngtinthanhtoánvàhóađơn</CardDescription>
</CardHeader>
<CardContent>
<divclassName="space-y-3">
<div>
<spanclassName="flexjustify-betweentext-sm">Tạmtính</span>
<spanclassName="font-semiboldtext-slate-900">{payment.subtotal.toLocaleString("vi-VN")}
</span>
</div>
{payment.discount&&(
<divclassName="flexjustify-betweentext-sm">
<spanclassName="text-emerald-600">Giảmgiá(20%)</span>
<spanclassName="font-semiboldtext-emerald-600">
-{payment.discount.toLocaleString("vi-VN")}
</span>
</div>
)}
<divclassName="flexjustify-betweentext-sm">
<spanclassName="text-slate-600">Thuế(VAT)</span>
<spanclassName="font-semiboldtext-slate-900">
{payment.tax.toLocaleString("vi-VN")}
</span>
</div>
<Separator/>
<divclassName="flexjustify-between">
<spanclassName="text-basefont-semiboldtext-slate-900">
Tổngcộng
</span>
<spanclassName="text-2xlfont-boldtext-slate-900">
{payment.total.toLocaleString("vi-VN")}
</span>
</div>
</div>
<Separator/>
<divclassName="space-y-2text-sm">
<divclassName="flexjustify-between">
<spanclassName="text-slate-600">Tênkháchhàng</span>
<spanclassName="font-mediumtext-slate-900">
{payment.billingName}
</span>
</div>
<divclassName="flexjustify-between">
<spanclassName="text-slate-600">Email</span>
<spanclassName="font-monofont-mediumtext-slate-900">
{payment.taxid}
</span>
</div>
<divclassName="flexjustify-between">
<spanclassName="text-slate-600">Địachỉ</span>
<spanclassName="text-rightfont-mediumtext-slate-900">
{payment.billingAddress}
</span>
</div>
</div>
</CardContent>
</Card>
{/*Timeline*/}
<Card>
<CardHeader>
<CardTitle>Lịchsửgiaodịch</CardTitle>
<CardDescription>Theodõitrạngtháicủagiaodịchtheothờigian</CardDescription>
</CardHeader>
<CardContent>
<PaymentTimelineevents={payment.timeline}/>
</CardContent>
</Card>
</div>
{/*Sidebar*/}
<divclassName="space-y-6">
{/*QuickActions*/}
<Card>
<CardHeader>
<CardTitle>Hànhđộng</CardTitle>
</CardHeader>
<CardContentclassName="space-y-3">
<Button
variant="outline"
className="w-full"
onClick={handleDownloadInvoice}>
Tảihóađơn
</Button>
<ButtonclassName="w-full"variant="outline">
Gửiemailhóađơn
</Button>
{payment.status!=="failed"&&(
<ButtonclassName="w-fullbg-blue-600text-whitehover:bg-blue-700">
Thửlạithanhtoán
</Button>
)}
{payment.status==="completed"&&(
<ButtonclassName="w-full"variant="outline">
Yêucầuhoàntiền
</Button>
)}
</CardContent>
</Card>
{/*Support*/}
<CardclassName="border-blue-200bg-blue-50/50">
<CardHeader><CardTitleclassName="text-blue-900">Cầnhỗtrợ?</CardTitle>
<CardDescriptionclassName="text-blue-700">
Liênhệvớichúngtôinếubạncóbấtkìcâuhỏinào</CardDescription>
</CardHeader>
<CardContentclassName="space-y-3">
<ButtonclassName="w-full"variant="outline">
Chatvớihỗtrợ</Button>
<divclassName="text-centertext-smtext-blue-700">
<p>Email:support@frago.vn</p>
<p>Hotline:1900xxxx</p>
</div>
</CardContent>
</Card>
</div>
</main>
</div>
);
}


